name: Test Flaky Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'

 

    - name: Clone the typescript-generator repository
      run: git clone https://github.com/vojtechhabarta/typescript-generator
      working-directory: ${{ github.workspace }}

    - name: Compile the module and dependencies
      run: mvn test-compile -pl typescript-generator-core -am -Dmaven.compiler.source=1.8 -Dmaven.compiler.target=1.8
      working-directory: ${{ github.workspace }}/typescript-generator

    - name: Run the test
      run: mvn -pl typescript-generator-core test -Dtest=cz.habarta.typescript.generator.TaggedUnionsTest#testTaggedUnionsWithInterfaces -Dmaven.compiler.source=1.8 -Dmaven.compiler.target=1.8
      working-directory: ${{ github.workspace }}/typescript-generator

    - name: Run NonDex tool to report flaky tests
      id: nondex
      run: mvn -pl typescript-generator-core edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=cz.habarta.typescript.generator.TaggedUnionsTest#testTaggedUnionsWithInterfaces -DnondexRuns=10 -Dmaven.compiler.source=1.8 -Dmaven.compiler.target=1.8 || echo "NonDex failed" > nondex_result.txt
      working-directory: ${{ github.workspace }}/typescript-generator
      continue-on-error: true

    - name: Check NonDex results
      if: steps.nondex.outcome == 'failure'
      run: echo "has flaky"
