name: Test Flaky Test

on:
  push:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          repository: vojtechhabarta/typescript-generator
          ref: caef58bfe55a8cd1fc5d7368c19e9ff818a7b7fa

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'  
          distribution: 'adopt'

      - name: Compile and Test
        run: |
          mvn test-compile -pl typescript-generator-core/pom.xml -am
          mvn test -pl typescript-generator-core/pom.xml -Dtest=cz.habarta.typescript.generator.JsonDeserializationTest#testWithConstructors
      - name: Get nondexTests
        run: nondexTests=$(git diff --name-status --diff-filter=AM ${{ github.event.before }} ${{ github.sha }} | grep /test/ | sed -e 's;.*test/java/;;' -e 's/.java//' -e 's;/;.;g' | tr '\n' ','); echo $nondexTests;
      - name: Run NonDex
        run: if [ ! -z $nondexTests ]; then printf "Running NonDex on tests:\n$nondexTests \n" ; mvn -B edu.illinois:nondex-maven-plugin:1.1.2:nondex  -DnondexRuns=10 -DfailIfNoTests=false -Dtest=$nondexTests ; fi
      - name: Find flakyTests 
        run: if [ -d ".nondex" ]; then flakyTests=$(awk ' !x[$0]++' .nondex/*/failures); fi
      - name: Output flakyTests
        run: if [ ! -z "$flakyTests" ]; then printf "Found flaky tests:\n$flakyTests \n" ; exit 1 ; else printf "No flaky tests found.\n" ; fi

    
